services:
#  mariadb:
#    image: 'mariadb:latest'
#    environment:
#      - 'MARIADB_DATABASE=mydatabase'
#      - 'MARIADB_PASSWORD=secret'
#      - 'MARIADB_ROOT_PASSWORD=verysecret'
#      - 'MARIADB_USER=myuser'
#    ports:
#      - '3306:3306'
  app:
    build:
      context: .
      dockerfile: docker/java/Dockerfile
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
  oracle:
    image: oracle/database:19.3.0-ee
    container_name: oracle19-java
    ports:
      - '1521:1521'
    environment:
      ORACLE_PWD: mypassword1
  node:
    image: node:20
    container_name: java_node
    build: docker/node
    volumes:
      - './:/var/app'
